name: Package repository
on: 
  pull_request:
    types: [closed]
jobs:
  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Run SBT Tests
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Run SBT Tests
      run: |
        echo "Running Tests!!"
        
    - name: Get most recent tag
      run: |
        git describe --abbrev=0 --tags
        echo "::set-output name=RECENT_TAG::$(git describe --abbrev=0 --tags)"
        echo "::set-output name=TAG_NAME::hello"
      id: recent_tag
    
    - name: Update tag number
      id: new_tag
      run: |
        echo toJSON(steps.recent_tag)
        echo ${{ steps.recent_tag.output.RECENT_TAG }}
        echo ${{ steps.recent_tag.output.TAG_NAME }}
        echo "refs/tags/${{ steps.recent-tag.output.RECENT_TAG }}"
 
    - name: Display head_ref and base_ref
      run: |
        echo head ref == ${{github.head_ref}}
        echo base ref == ${{github.base_ref}}
    
#   publish:
#     needs: test
#     runs-on: ubuntu-latest
#     name: Publish artifact
#     steps:
#     - name: Publish repo
#       run: |
#         echo "publishing..."



