name: Package repository
on: [pull_request]
jobs:
  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Run SBT Tests
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run SBT Tests
      run: |
        echo "Running Tests!!"
    - name: Get Latest Commit
      run: |
        git describe --abbrev=0 --tags
    - name: Display head_ref and base_ref
      run: |
        echo head ref == ${{github.head_ref}}
        echo base ref == ${{github.base_ref}}
    
#   publish:
#     needs: test
#     runs-on: ubuntu-latest
#     name: Publish artifact
#     steps:
#     - name: Publish repo
#       run: |
#         echo "publishing..."



