name: Package repository
on: 
  pull_request:
    types: [closed]
jobs:
  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Run SBT Tests
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Run SBT Tests
      run: |
        echo "Running Tests!!"
        
    - name: Get most recent tag
      id: recent-tag
      run: echo '::set-output name=RECENT_TAG::$${{ git describe --abbrev=0 --tags }}'
    
    - name: Update tag number
      id: new-tag
      run: |
        echo "refs/tags/${{ steps.recent-tag.output.RECENT_TAG }}"
      
#     - name: Create tag
#       uses: actions/github-script@v3
#       with:
#         github-token: ${{ github.token }}
#         script: |
#           github.git.createRef({
#             owner: context.repo.owner,
#             repo: context.repo.repo,
#             ref: "refs/tags/${{ steps.recent-tag.output.RECENT_TAG }}",
#             sha: context.sha
#           })

    - name: Display head_ref and base_ref
      run: |
        echo head ref == ${{github.head_ref}}
        echo base ref == ${{github.base_ref}}
    
#   publish:
#     needs: test
#     runs-on: ubuntu-latest
#     name: Publish artifact
#     steps:
#     - name: Publish repo
#       run: |
#         echo "publishing..."



