name: Get Semantic Version for branch
on: 
  create
jobs:
  create:
    runs-on: ubuntu-latest
    name: Create semantic version for the branch
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Parse semver
      if: ${{ contains(github.ref, 'refs/heads') }}
      run: |
        ls
